dist: xenial
language: python
python:
  - "3.8"
compiler:
  - gcc
install:
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt
script:
  - coverage run -m unittest discover tests
  - python -m unittest tests/test_deft_pascal_lexer.py
  - python -m unittest tests/test_deft_pascal_parser.py
  - python -m unittest tests/test_compiler_internals.py
  - python -m unittest tests/test_deft_pascal_compiler.py
  - python -m unittest tests/test_code_generation.py
after_success:
  - coveralls
