dist: xenial
language: python
python:
  - "3.8"
compiler:
  - gcc
install:
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt
before_script:
  - CC_TEST_REPORTER_ID=17b6f0d248c948db0156cad289d5b8e989e26dcb5d5a341c876484719e4247fd
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - coverage run --omit */lib/* -m unittest discover tests
  - python -m unittest tests/test_compiler_internals.py
  - python -m unittest tests/test_symbols.py
  - python -m unittest tests/test_symbol_table.py
  - python -m unittest tests/test_deft_pascal_lexer.py
  - python -m unittest tests/test_deft_pascal_parser.py
  - python -m unittest tests/test_deft_pascal_compiler.py
  - python -m unittest tests/test_code_generation.py
after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - coveralls -v
  - coverage report
