dist: bionic
language: python
python:
  - "3.8"
compiler:
  - clang
install:
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - gcc --version
  - clang --version
  - cc --version
script:
  - coverage run --omit */Lib/* -m unittest
after_script:
  - coverage xml
  - ./cc-test-reporter after-build -r 17b6f0d248c948db0156cad289d5b8e989e26dcb5d5a341c876484719e4247fd --exit-code $TRAVIS_TEST_RESULT
after_success:
  - coveralls -v
  - coverage report
