name: Deft Pascal Reborn Tests

on:
  push:
    branches: [ $default-branch, dev ]
  pull_request:
    branches: [ $default-branch, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install mccabe
        
        python -m pip install pep8-naming
        python -m pip install flake8-variables-names
        python -m pip install flake8-eradicate
        python -m pip install flake8-comprehensions
        python -m pip install flake8-return        
        
        python -m pip install coverage
        python -m pip install python-coveralls
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Parser - Code Style Compliance
      run: |
        flake8 --max-line-length 120 --show-source --statistics --exit-zero --max-complexity=10 components/deft_pascal_parser_3.py
      continue-on-error: true
    - name: Parser - Unit Test and Coverage report
      run: |
        coverage erase
        coverage run -a -m --source=components unittest -v tests.test_deft_pascal_parser
        coverage report -i -m
      continue-on-error: true
    - name: Parser - Complexity
      run: |
        python -m mccabe --min 5 components/deft_pascal_parser_3.py
      continue-on-error: true
    - name: All - Code Style Compliance
      run: |
        flake8 . --exclude=tests,scrapbook,obsoletes,grammars,.github --max-line-length 120 --show-source --statistics --exit-zero --max-complexity=10
      continue-on-error: true
    - name: All - Unit Test and Coverage report
      run: |
        coverage erase
        coverage run -a -m unittest discover -v -s tests
        coveralls -v
        coverage report -i -m
      continue-on-error: true
    - name: Coveralls GitHub Action
      # You may pin to the exact commit or the version.
      # uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
